# Generated by Django 4.1.12 on 2023-10-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_mensajes', models.PositiveIntegerField()),
                ('ultimo_mensaje', models.TextField()),
            ],
            options={
                'db_table': 'conversaciones',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('fotoURL', models.URLField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tags', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=100)),
                ('cierre', models.DateField()),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('fotoURL', models.URLField()),
                ('reputacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('telefono', models.CharField(max_length=20)),
                ('vivienda', models.CharField(max_length=100)),
                ('contrasenya', models.CharField(max_length=100)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('listaConver', models.ManyToManyField(to='elrastroapp.conversacion')),
                ('productosVenta', models.ManyToManyField(to='elrastroapp.producto')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elrastroapp.producto')),
                ('pujador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elrastroapp.usuario')),
            ],
            options={
                'db_table': 'pujas',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='pujas',
            field=models.ManyToManyField(related_name='productos_pujados', to='elrastroapp.puja'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elrastroapp.usuario'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_recibidas', to='elrastroapp.usuario'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_enviadas', to='elrastroapp.usuario'),
        ),
    ]
